/**
 * toolEndpoint()/endpointToTool() — resolve a registered MCP tool name to the
 * {method, path} of the real Dockhand endpoint it calls (and back), using the
 * generated `src/openapi/tool-endpoint-map.ts` registry as ground truth.
 *
 * The map itself is generated by scripts/generate-tool-endpoint-map.mjs (see that
 * file's header for why it is an explicit, generated-but-corrected registry rather
 * than a pure runtime derivation from client.<method>(...) call sites).
 */
import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { toolEndpoint, endpointToTool } from '../src/openapi/tool-endpoint.js';
import { TOOL_ENDPOINT_MAP } from '../src/openapi/tool-endpoint-map.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOOLS_DIR = join(__dirname, '..', 'src', 'tools');

describe('toolEndpoint', () => {
  it('resolves a known tool to its {method, path}', () => {
    expect(toolEndpoint('list_git_stacks')).toEqual({ method: 'GET', path: '/api/git/stacks' });
  });

  it('returns undefined for a tool with no registry entry (e.g. get_prometheus_metrics)', () => {
    expect(toolEndpoint('get_prometheus_metrics')).toBeUndefined();
  });

  it('returns undefined for a name that is not a tool at all', () => {
    expect(toolEndpoint('not_a_real_tool')).toBeUndefined();
  });
});

describe('endpointToTool', () => {
  it('resolves a known endpoint back to its tool name', () => {
    expect(endpointToTool('GET', '/api/environments')).toBe('list_environments');
  });

  it('is case-insensitive on the HTTP method', () => {
    expect(endpointToTool('get', '/api/environments')).toBe('list_environments');
  });

  it('returns undefined for an endpoint no tool serves', () => {
    expect(endpointToTool('GET', '/api/does/not/exist')).toBeUndefined();
  });

  it('round-trips every registry entry: endpointToTool(toolEndpoint(name)) resolves back to a tool serving that endpoint', () => {
    for (const [name, entry] of Object.entries(TOOL_ENDPOINT_MAP)) {
      const resolved = endpointToTool(entry.method, entry.path);
      expect(resolved, name).toBeDefined();
      // Not necessarily the SAME tool name (two tools may share an endpoint), but the
      // resolved tool must itself map back to the identical {method, path}.
      expect(toolEndpoint(resolved!)).toEqual(entry);
    }
  });
});

describe('tool-endpoint-map completeness', () => {
  function extractAllToolNames(): string[] {
    const files = readdirSync(TOOLS_DIR).filter((f) => f.endsWith('.ts') && f !== 'index.ts');
    const names: string[] = [];
    const pattern = /registerTool\s*\(\s*server\s*,\s*['"]([^'"]+)['"]/g;
    for (const file of files) {
      const content = readFileSync(join(TOOLS_DIR, file), 'utf-8');
      let m: RegExpExecArray | null;
      while ((m = pattern.exec(content)) !== null) {
        names.push(m[1]);
      }
    }
    return names;
  }

  it('every registered tool has an entry, except the documented get_prometheus_metrics gap', () => {
    const allNames = extractAllToolNames();
    const missing = allNames.filter(
      (name) => !(name in TOOL_ENDPOINT_MAP) && name !== 'get_prometheus_metrics',
    );
    expect(missing, `\n${missing.join('\n')}`).toEqual([]);
  });

  it('every map entry corresponds to an actually-registered tool', () => {
    const allNames = new Set(extractAllToolNames());
    const dangling = Object.keys(TOOL_ENDPOINT_MAP).filter((name) => !allNames.has(name));
    expect(dangling, `\n${dangling.join('\n')}`).toEqual([]);
  });
});
